info:
  component: Edge Server

---

server:
  port: 8765


---

zuul:
  prefix: /api
  #forceOriginalQueryStringEncoding: true
  ignoredServices: "*"
  routes:
    myservice:
      path: /myservice/**
      serviceId: myservice
      url: http://httpbin.org/

